### ISSUE TITLE
api server.  PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by electronoob** [ArpitLinux/ShazamMovies#2]
steps to reproduce:

use the ui to upload an audio file to the api

PS C:\Users\user\git\git-rubyteam\ShazamMovies\backend> node .\app.js
Server is Successfully Running and App is listening on port 3000
PayloadTooLargeError: request entity too large
    at readStream (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\raw-body\index.js:156:17)
    at getRawBody (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\raw-body\index.js:109:12)
    at read (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\body-parser\lib\read.js:79:3)
    at jsonParser (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\body-parser\lib\types\json.js:135:5)
    at Layer.handle [as handle_request] (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\express\lib\router\index.js:328:13)
    at C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\express\lib\router\index.js:280:10)
    at expressInit (C:\Users\user\git\git-rubyteam\ShazamMovies\backend\node_modules\express\lib\middleware\init.js:40:5)

**Comment by electronoob** [comment]
i didn't really explore why but i changed the first bodyParser.json to modify the limit. for whatever reason your other lines, despite having it set, didn't work. haven't got time at the moment to explore so just mentioning here is an FYI
   
    const app = express();
    app.use(bodyParser.json({limit: '10mb'}))
